def display_board(board):
  #  clear_output()
    print(' | |')
    print(board[7] + "|" + board[8] + "|" + board[9])
    print(' | |')
    print('-----')
    print(' | |')
    print(board[4] + "|" + board[5] + "|" + board[6])
    print(' | |')
    print('------')
    print(' | |')
    print(board[3] + "|" + board[2] + "|" + board[1])
    print(' | |')
test_board = [' ']*10
display_board(test_board)